// <auto-generated />
namespace RegionalShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class opis_produktu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(opis_produktu));
        
        string IMigrationMetadata.Id
        {
            get { return "202011121544217_opis_produktu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
