// <auto-generated />
namespace RegionalShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Email_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_change));
        
        string IMigrationMetadata.Id
        {
            get { return "202111220916296_Email_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
